.PHONY: generate_ldscripts FORCE

FORCE:

generate_ldscripts : mem.ld sections.ld

%.ld : $(LDSCRIPT_PATH)/%.ld.h
	@echo "Generating $@ ..."
	"$(CC)" -I "$(BSP_CONFIG_DIR)" -I "$(MIDDLEWARE_CONFIG_DIR)" $(PRE_BUILD_EXTRA_DEFS) -imacros "$(APP_CONFIG_H)" $(LD_DEFS) -Ddg_configDEVICE=$(DEVICE) -MMD -MP -MF"$(@:%=%.d)" -MT"$(@)" -E -P -c "$<" -o "$@"

-include mem.ld.d
-include sections.ld.d

freertos_retarget.elf : mem.ld sections.ld
