LDSCRIPT_PATH=../ldscripts

.PHONY: main-build pre-build generate_ldscripts FORCE
main-build : | pre-build

FORCE:

generate_ldscripts : mem.ld sections.ld

generate_obj_dump_file: $(FILENAME)_objdump.txt

%.ld : $(LDSCRIPT_PATH)/%.ld.h
	@echo "Generating $@ ..."
	"$(CC)" -I "$(BSP_CONFIG_DIR)" -I "$(MIDDLEWARE_CONFIG_DIR)" $(PRE_BUILD_EXTRA_DEFS) -imacros "$(APP_CONFIG_H)" $(LD_DEFS) -Ddg_configDEVICE=$(DEVICE) -MMD -MP -MF"$(@:%=%.d)" -MT"$(@)" -E -P -c "$<" -o "$@"


%_objdump.txt: %.elf
	"arm-none-eabi-objdump" -S $< > $@
